spring:
  profiles:
    default: local

  datasource:
    url: jdbc:h2:mem:~/oopPractice
    driver-class-name: org.h2.Driver
    username: sa
    password:


  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc.batch_size: 100
        order_inserts: true
        order_updates: true
---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true
